/* post table */
CREATE TABLE POST(
 POSTNO NUMBER PRIMARY KEY,
 EMAIL VARCHAR2(1000),
 PLAN NUMBER(38), -- foreign key 연결시 자료형이 달라 varchar2 > number로 변경
 TITLEIMAGE VARCHAR2(1000),
 IMAGES VARCHAR2(1000),
 CONTENT VARCHAR2(1000),
 HASHTAG VARCHAR2(1000),
 REGDATE DATE DEFAULT sysdate,
 VIEWS NUMBER DEFAULT 0,
 AUTHORITY VARCHAR2(1000),
 
 CONSTRAINT fk_userid_post FOREIGN KEY(email) REFERENCES userinfo(userEmail) ON DELETE CASCADE,
 CONSTRAINT fk_plan_post FOREIGN KEY(plan) REFERENCES plan_mst(planNum) ON DELETE CASCADE
);
CREATE SEQUENCE POST_NO_SEQ NOCACHE;

/* post_like table */
CREATE TABLE POST_LIKE(
 POSTLIKENO number PRIMARY KEY,
 POSTNO NUMBER,
 EMAIL VARCHAR2(1000),
 LIKES NUMBER DEFAULT 0,
 
 CONSTRAINT fk_postno_postlike FOREIGN KEY(postno) REFERENCES post(postno) ON DELETE CASCADE,
 CONSTRAINT fk_email_postlike FOREIGN KEY(email) REFERENCES userinfo(userEmail) ON DELETE CASCADE
);

CREATE SEQUENCE POST_LIKE_SEQ NOCACHE;

/* post_comments table */
CREATE TABLE COMMENTS (
 COMMENTNO NUMBER PRIMARY KEY,
 POSTNO NUMBER,
 EMAIL  VARCHAR2(100),
 CONTENT VARCHAR2(1000),
 TIME DATE DEFAULT sysdate,
 grp number DEFAULT 0,
 grpl number DEFAULT 0,
 grps number DEFAULT 0,
 
 CONSTRAINT fk_postno_comments FOREIGN KEY(postno) REFERENCES post(postno) ON DELETE CASCADE,
 CONSTRAINT fk_email_comments FOREIGN KEY(email) REFERENCES userinfo(userEmail) ON DELETE CASCADE
);

CREATE SEQUENCE COMMENTS_SEQ NOCACHE;

CREATE TABLE POST_VIEW(
 POSTVIEWNO number PRIMARY KEY,
 POSTNO NUMBER,
 EMAIL VARCHAR2(1000),
 VIEWS NUMBER DEFAULT 0,
 
 CONSTRAINT fk_postno_postview FOREIGN KEY(postno) REFERENCES post(postno) ON DELETE CASCADE,
 CONSTRAINT fk_email_postview FOREIGN KEY(email) REFERENCES userinfo(userEmail) ON DELETE CASCADE
);

CREATE SEQUENCE post_view_seq NOCACHE;

CREATE TABLE post_dt (
 postNo NUMBER NOT NULL,
 planNum NUMBER NOT NULL,
 planDtNum NUMBER NOT NULL,
 location VARCHAR2(1000) NOT NULL,
 latitude VARCHAR2(30), 
 longitude VARCHAR2(30),
 
 CONSTRAINT fk_postno_postdt FOREIGN KEY(postno) REFERENCES post(postno) ON DELETE CASCADE,
 CONSTRAINT fk_planNum_postdt FOREIGN KEY(planNum) REFERENCES plan_mst(planNum) ON DELETE CASCADE,
 CONSTRAINT fk_planDtNum_postdt FOREIGN KEY(planDtNum) REFERENCES plan_dt(planDtNum) ON DELETE CASCADE
);


/* 작업용 */

DROP SEQUENCE post_view_seq;
DROP SEQUENCE post_no_SEQ;
DROP SEQUENCE COMMENTS_SEQ;
DROP SEQUENCE POST_LIKE_SEQ;
DROP TABLE post_view_seq;
DROP TABLE POST;
DROP TABLE POST_LIKE;
DROP TABLE COMMENTS;
DROP TABLE POST_VIEW;
DROP TABLE post_dt;

SELECT * FROM COMMENTS;

SELECT COUNT(COMMENTNO) comments 
FROM POST a, COMMENTS b 
WHERE a.postno = b.postno;

SELECT a.CONTENT, COUNT(b.postno) 
FROM POST a, COMMENTS b 
WHERE a.postno = b.postno(+);            


SELECT * FROM POST,comments;

SELECT location, hashtag, (SELECT count(*) 
                           FROM COMMENTS 
                           WHERE POSTNO = 14) cnt 
FROM POST ;



